name: Build OpenWrt for Orange Pi R1
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 更新feeds并安装
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 最后一步编译
        run: |
          FORCE=1 make 

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: bin/targets/sunxi/cortexa7/

      - name: final check (rm-able)
        run: |
          ls bin/targets/sunxi/cortexa7
          ip -s link

